# Generated by Django 3.1.1 on 2020-09-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='../images/NoImageFound.jpg', upload_to='images/'),
        ),
    ]
