# Generated by Django 3.1.1 on 2020-09-22 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_one', models.CharField(default='', max_length=50)),
                ('street_two', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='', max_length=15)),
                ('zipcode', models.CharField(default='', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.address')),
            ],
        ),
    ]
