# Generated by Django 3.1.1 on 2020-10-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20201004_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default='test@gmail.com', max_length=50),
            preserve_default=False,
        ),
    ]
